# Generated by Django 6.0.2 on 2026-02-08 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('category', models.CharField(choices=[('food', 'Продукты'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения'), ('health', 'Здоровье'), ('shopping', 'Покупки'), ('utilities', 'Коммунальные'), ('other_expense', 'Другое'), ('salary', 'Зарплата'), ('freelance', 'Фриланс'), ('investment', 'Инвестиции'), ('gift', 'Подарок'), ('other_income', 'Другое')], max_length=50, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
    ]
